{
  allSoftwareApplications {
    id: _id
    name
    alternateName
    description
    identifier
    url
    author {
      name
    }
    availableOnDevice {
      name
    }
    featureList {
      name
    }
    operatingSystems {
      name
    }
  }
  allSendActions {
    duration
    fromLocation {
      _id
    }
    toLocation {
      _id
    }
  }
  allSoftwareSourceCodes {
    targetProduct {
      _id
    }
    programmingLanguages {
      name
    }
  }
}
